# Generated by Django 4.1 on 2022-08-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='title',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
