# Generated by Django 4.1 on 2022-08-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_snippet_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='project',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
