# Generated by Django 4.1 on 2022-08-30 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_alter_snippet_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_snippets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
