# Generated by Django 4.1 on 2022-08-31 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_snippet_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='snippets.snippet'),
        ),
    ]
